### ISSUE TITLE
Bug when comparing policy to value iteration

### ISSUE THREAD

**Issue by Jbwasse2** [tauhid03/MarkovChainAnalysis#11]
I am currently comparing the value and policy iteration code to make sure the results are the same. I have made the following test code
`  
Ps, R = multiagent(S=10, N=2)  
Ps2 = Ps  
R2 = R  
vi_policy = KronPolicyIteration(Ps, R, 0.95, skip_check=True)  
policy_results = vi_policy.run()  
vi_value = KronValueIteration(Ps2, R2, 0.95, skip_check=True)  
value_results = list(vi_value.run())`

and the results cause the KronValueIteration code to fail, but if KronValueIteration is first it doesn't seem to fail.

**Comment by alexandroid000** [comment]
Probably a pass by reference issue - code like `Ps2 = Ps` does not copy Ps, and both `Ps2` and `Ps` refer to the same object.

To solve: 
`from copy import deepcopy`
`Ps2 = deepcopy(Ps)`

**Comment by Jbwasse2** [comment]
Yep that fixed it.
